### ISSUE TITLE
Arguments error when doing `ng build --prod --build-optimizer`[IGNORE]

### ISSUE THREAD

**Issue by ihouse10** [angular-patterns/ng-bootstrap-modal#1]
I tried following this example in the README.md to pass parameters to the ok(param) function (it's near the bottom of the page):

    param:string;
    constructor(private modalService:ModalService) {
        this.param = this.modalService.getValue();
    }
    submit() {
         this.param = 'something else';
         this.modalService.ok(this.param);
    }
When I tried to build my project for production using the Anglular-cli command `ng build --prod --build-optimizer`, I get the following error on the terminal `Expected 0 arguments, but got 1.` and it points to the ModalService.ok(this.param) function. I think this might be an issue with the module. It does work fine when I test it on by starting the NG Live Development Server.

**Comment by ihouse10** [comment]
Please delete this issue. I made a mistake. Sorry for inconvenience. This is a great module for Angular.

**Comment by pixelbits-mk** [comment]
I'm glad that you were able to resolve the issue.  If you are using bootstrap heavily, I recommend this component which has a modal component available: https://www.npmjs.com/package/ngx-bootstrap
